name: Monitor FAA ACS Documents

on:
  schedule:
    # Run every Monday at 9 AM EST (FAA typically updates documents on weekdays)
    - cron: '0 14 * * 1'
  workflow_dispatch: # Allow manual triggering
  
env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  monitor-acs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Monitor FAA ACS Documents
        run: |
          python scripts/monitor.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Process Changes (if any)
        if: success()
        run: |
          python scripts/pdf_processor.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'FAA ACS Monitor Bot'
          git config --global user.email 'bot@faa-acs-monitor.local'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "📄 Updated ACS documents - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
            
            # Create issue for changes
            if [ -f "data/metadata/changes.json" ]; then
              python scripts/create_change_notification.py
            fi
          else
            echo "No changes detected"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: monitoring-logs
          path: |
            logs/
            data/metadata/
          retention-days: 30